packages:
  # all packages in subdirs of packages/ and components/
  # - 'packages/**'
  - 'packages/bonde-admin'
  - 'packages/bonde-admin-canary'
  - 'packages/bonde-public'
  - 'packages/bonde-styleguide'
  - 'packages/bonde-webpage'
  - 'components/**'
  # exclude packages that are inside test/ directories
  - '!**/test/**'
